- betfairlightweight/compat.py
- betfairlightweight/resources/baseresource.py
- tests/test_baseclient.py
This PR addresses the problems raised in #24. 
I would suggest possibly setting up error testing on https://www.appveyor.com/ for windows if it isn't a big inconvenience. These issues were caught through CI testing on conda-forge.
> Fix windows test failures

- betfairlightweight/__init__.py
- betfairlightweight/endpoints/betting.py
- betfairlightweight/endpoints/racecard.py
- betfairlightweight/resources/baseresource.py
- betfairlightweight/resources/bettingresources.py
- betfairlightweight/resources/racecardresources.py
- betfairlightweight/resources/streamingresources.py
- tests/resources/racecard.json
- tests/test_racecardresources.py
- tests/tools_seaders.py
Hi Liam,
Thanks a bunch for this library, it's been crazy useful for me, from shifting over from manually working with the REST API in Python.
I've been using it with PyCharm, and while it made my life easier, the lack of class definitions, and docstrings does slow down my devlopment speed, so I've added a ton of them, as well as a tool to auto-generate and add them to the classes.
Please consider this pull request, and get back to me with any other things you'd like me to change.
Thanks,
seaders.
> Docstrings, tooling and fixes

- betfairlightweight/__init__.py
- betfairlightweight/utils.py
- tests/test_utils.py
> price check fixed

- betfairlightweight/__init__.py
- betfairlightweight/utils.py
- tests/test_utils.py
> update_available updated to handle unwanted update

- betfairlightweight/__init__.py
- betfairlightweight/resources/__init__.py
- betfairlightweight/resources/bettingresources.py
- betfairlightweight/resources/racecardresources.py
Create a dirty "Slotable" class to enable pickling and unpickling of "Slotty" objects (objects with __slots__).
Import MarketDefinition and MarketDefinitionRunner in resources __init__.
> Create a dirty "Slotable" class to enable pickling and unpickling

- betfairlightweight/__init__.py
- betfairlightweight/resources/bettingresources.py
> clean up to marketbook/runnerbook when requesting orders

- betfairlightweight/resources/streamingresources.py
Resolves liampauling/betfairlightweight#92
> Handle hc field when constructing OrderBookRunner

- betfairlightweight/resources/streamingresources.py
Resolves liampauling/betfairlightweight#97
> Make rac, rc kwargs on UnmatchedOrder

- betfairlightweight/__init__.py
- betfairlightweight/resources/bettingresources.py
- betfairlightweight/resources/streamingresources.py
- tests/test_bettingresources.py
streaming orders with sp orders fixed
tests fixed/added
> sp orders fixed

- betfairlightweight/apiclient.py
- betfairlightweight/endpoints/__init__.py
- betfairlightweight/endpoints/historical.py
Quick hack to get access to the historical endpoints recently released.
> Add historical endpoints

- betfairlightweight/resources/streamingresources.py
- tests/unit/test_streamingresources.py
Fixes https://github.com/liampauling/betfair/issues/157
> Handle missing openDate in MarketDefinition

- betfairlightweight/__init__.py
- betfairlightweight/streaming/cache.py
- tests/unit/test_cache.py
**kwargs added to unmatchedorder
version bump
tests fixed
> lsrc added to unmatchedorder

- HISTORY.rst
- betfairlightweight/__init__.py
- build.sh
- requirements.txt
- setup.py
HISTORY.rst added
ciso and requests upgraded
> build.sh added

- HISTORY.rst
- betfairlightweight/__init__.py
- betfairlightweight/baseclient.py
- betfairlightweight/endpoints/login.py
- betfairlightweight/resources/bettingresources.py
- betfairlightweight/streaming/cache.py
- tests/unit/test_baseclient.py
- tests/unit/test_login.py
currently not working (19/11/18)
> identity_cert_urls added (migration 20/12/18)

- betfairlightweight/baseclient.py
- tests/unit/test_baseclient.py
> certificate endpoints updated

- README.md
- betfairlightweight/endpoints/betting.py
- betfairlightweight/streaming/betfairstream.py
- examples/examplestreaming.py
- examples/examplestreaminghistorical.py
- tests/integration/test_historicalstream.py
- tests/unit/test_betfairstream.py
> _async renamed to async_ in betting endpoint

- betfairlightweight/streaming/betfairstream.py
running handling added to empty string to prevent error being raised mid recv
> closes #165

- betfairlightweight/filters.py
- tests/unit/test_filters.py
> closes #175

- README.md
- betfairlightweight/endpoints/streaming.py
- betfairlightweight/streaming/__init__.py
- betfairlightweight/streaming/betfairstream.py
- tests/unit/test_betfairstream.py
- tests/unit/test_streamingendpoint.py
HistoricalGeneratorStream added
tests improved
> closes #163

- betfairlightweight/streaming/cache.py
- tests/unit/test_cache.py
> orders list added during serialise to prevent RuntimeError

- .travis.yml
- HISTORY.rst
- README.md
- appveyor.yml
- betfairlightweight/__init__.py
- betfairlightweight/resources/accountresources.py
- betfairlightweight/streaming/cache.py
- requirements.txt
- setup.py
- tests/unit/test_cache.py
requests upgraded and unpinned from latest (expecting tests to fail..)
> version / history update

- .travis.yml
- HISTORY.rst
- README.md
- appveyor.yml
- betfairlightweight/__init__.py
- betfairlightweight/baseclient.py
- betfairlightweight/compat.py
- betfairlightweight/streaming/betfairstream.py
- setup.py
py2 removed from compat.py
p2 removed from build/testing/setup
> remove py2 creation of NullHandler

- HISTORY.rst
- README.md
- betfairlightweight/apiclient.py
- betfairlightweight/baseclient.py
- betfairlightweight/endpoints/streaming.py
- betfairlightweight/exceptions.py
- betfairlightweight/metadata.py
- betfairlightweight/streaming/betfairstream.py
- betfairlightweight/streaming/listener.py
- betfairlightweight/streaming/stream.py
- tests/unit/test_baseclient.py
- tests/unit/test_betfairstream.py
- tests/unit/test_metadata.py
- tests/unit/test_stream.py
- tests/unit/test_streamingendpoint.py
> metadata update

- HISTORY.rst
- README.md
- betfairlightweight/__init__.py
- betfairlightweight/__version__.py
- betfairlightweight/baseclient.py
- betfairlightweight/utils.py
- setup.py
- tests/unit/test_baseclient.py
- tests/unit/test_utils.py
setup refactor to use __version__
> __version__ added

- HISTORY.rst
- betfairlightweight/apiclient.py
- betfairlightweight/baseclient.py
- betfairlightweight/filters.py
- examples/examplehistoricdata.py
- examples/exampleinplayservice.py
- examples/exampleracecard.py
- examples/examplestreaming.py
- examples/examplestreaminghistorical.py
> session can be passed to client (defaulting to requests)

- README.md
- docs/streaming.md
> readme bugfix

- betfairlightweight/endpoints/baseendpoint.py
- betfairlightweight/endpoints/historic.py
- betfairlightweight/endpoints/inplayservice.py
- betfairlightweight/endpoints/keepalive.py
- betfairlightweight/endpoints/login.py
- betfairlightweight/endpoints/logininteractive.py
- betfairlightweight/endpoints/logout.py
- betfairlightweight/endpoints/navigation.py
- betfairlightweight/endpoints/racecard.py
- tests/unit/test_historical.py
- tests/unit/test_inplayservice.py
- tests/unit/test_racecard.py
- tests/unit/tools.py
response.content used instead of text, when text is used requests has to work out the encoding
https://github.com/psf/requests/issues/3917
> closes #268

- betfairlightweight/streaming/listener.py
- tests/unit/test_listener.py
https://forum.developer.betfair.com/forum/developer-program/announcements/30597-exchange-stream-api-release-connection-throttling-24th-february
> add connectionsAvailable to listener + improve logging

- betfairlightweight/compat.py
- betfairlightweight/endpoints/baseendpoint.py
- betfairlightweight/endpoints/historic.py
- betfairlightweight/endpoints/inplayservice.py
- betfairlightweight/endpoints/keepalive.py
- betfairlightweight/endpoints/login.py
- betfairlightweight/endpoints/logininteractive.py
- betfairlightweight/endpoints/logout.py
- betfairlightweight/endpoints/navigation.py
- betfairlightweight/endpoints/racecard.py
- betfairlightweight/streaming/listener.py
- requirements.txt
- tests/unit/test_baseendpoint.py
- tests/unit/test_compat.py
- tests/unit/test_inplayservice.py
- tests/unit/test_keepalive.py
- tests/unit/test_login.py
- tests/unit/test_logininteractive.py
- tests/unit/test_logout.py
- tests/unit/test_navigation.py
- tests/unit/test_racecard.py
see https://github.com/ultrajson/ultrajson/issues/371
> removal of json_loads func now that ujson handles floats correctly

- HISTORY.rst
- docs/advanced.md
- docs/index.md
- requirements.txt
- tests/unit/test_baseendpoint.py
- tests/unit/test_baseresource.py
- tests/unit/test_listener.py
c based libraries made optional for windows install
docs update
> ujson upgraded to 2.0.3

- docs/advanced.md
> NemID login example added

- HISTORY.rst
- README.md
- betfairlightweight/__version__.py
- betfairlightweight/endpoints/streaming.py
- betfairlightweight/resources/bettingresources.py
- betfairlightweight/streaming/betfairstream.py
- docs/streaming.md
- examples/examplestreaminghistorical.py
- requirements.txt
- tests/integration/test_historicalstream.py
- tests/unit/test_betfairstream.py
- tests/unit/test_streamingendpoint.py
> closes #301

- setup.py
This change is a proposal to fix the issue described there
https://github.com/liampauling/betfair/issues/366
> Rename _requires into extras_require

- .github/workflows/test.yml
- HISTORY.rst
- README.md
- betfairlightweight/__version__.py
- betfairlightweight/resources/racecardresources.py
- requirements-test.txt
- setup.py
> Handle missing values in Going resource

- HISTORY.rst
- betfairlightweight/__version__.py
- betfairlightweight/streaming/cache.py
- requirements-test.txt
> history and version

- betfairlightweight/resources/streamingresources.py
- tests/resources/ccms/ccm0.json
- tests/resources/ccms/ccm1.json
- tests/resources/ccms/ccm2.json
- tests/resources/ccms/ccm3.json
- tests/resources/ccms/ccm4.json
- tests/resources/ccms/ccm5.json
- tests/resources/ccms/ccm6.json
- tests/test_streamingresources.py
Need some feedback from Neil before this is ready to merge - see #460
> Resolve #460:  Breaking changes to cricket feed

- betfairlightweight/streaming/cache.py
> prevent using tv when using PRO betfair data

- betfairlightweight/resources/streamingresources.py
- tests/resources/ccms/ccm0.json
- tests/resources/ccms/ccm1.json
- tests/resources/ccms/ccm2.json
- tests/resources/ccms/ccm3.json
- tests/resources/ccms/ccm4.json
- tests/resources/ccms/ccm6.json
- tests/test_streamingresources.py
> Add "modified" field to CricketIncident

- betfairlightweight/baseclient.py
- tests/test_baseclient.py
> #279 Stop prepending pardir to certs path
