betcode-org/betfair

betfairlightweight/streaming/betfairstream.py
tests/test_betfairstream.py

The daemon kwarg in threading.Thread was added in python 3 - by setting the daemon field after constructing the Thread object, the functionality remains the same, but the code is now compatible with python 2.7

python 2.7 threading.Thread has no daemon kwarg

---

setup.py

If I try to install from a new virtualenv (so no requests installed), I get the following error:
```
(venv) [fra@grigio test]$ pip install betfairlightweight
Collecting betfairlightweight
Downloading betfairlightweight-0.9.3.tar.gz (63kB)
100% |████████████████████████████████| 71kB 387kB/s 
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-RQBb_5/betfairlightweight/setup.py", line 4, in <module>
from betfairlightweight.__init__ import __version__
File "betfairlightweight/__init__.py", line 1, in <module>
from .apiclient import APIClient
File "betfairlightweight/apiclient.py", line 1, in <module>
from .baseclient import BaseClient
File "betfairlightweight/baseclient.py", line 1, in <module> …
```

Read __version__ with regex to avoid ImportError

---

betfairlightweight/apiclient.py
betfairlightweight/baseclient.py
betfairlightweight/exceptions.py
tests/test_baseclient.py

1. Aadded the `cert_files` kwarg, this way it doesn't break backward compatibility.
2. Added a test case for cert_files, and one for certs passed as relative path.
3. Changed `CertsError` to show the path the user passed

Add cert_files kwarg to APIClient

---

betfairlightweight/streaming/stream.py
tests/test_stream.py

Makes the function around 10x faster on microbenchmarks.
Since it's something that can be potentially be called lots of times, I thought it was worth tweaking it a bit to avoid the int -> dt -> int conversions.
Before:
```
def latency1(dt)
return (datetime.datetime.utcnow() - datetime.datetime.utcfromtimestamp(dt / 1e3)).total_seconds()
```
After:
```
def latency2(dt):
return time.time() - dt /1e3
```

Compute stream latency directly from unix timestamp

---

.gitignore
tests/test_baseclient.py

I was finally getting around to having another go at building a conda-forge package for `betfairlightweight` and noticed that although the initial issue appears to have been resolved, subsequent changes to the tests were causing failures on Windows due to differences in path separator conventions. This PR makes tests involving paths platform-independent. 
Once these changes have been approved and merged and a new release is made, I think we should be good to go on conda-forge. 
I have access to both OSX and Windows machines to test and fix issues like this, but it would be helpful to add a Windows-based CI to run the tests automatically. See https://github.com/liampauling/betfairlightweight/issues/47

Make test_baseclient tests involving paths cross-platform

---

betfairlightweight/__init__.py
betfairlightweight/streaming/listener.py
betfairlightweight/streaming/stream.py

Top level library logger set up with a NullHandler following the convention of the `requests` library as mentioned [here](http://docs.python-guide.org/en/latest/writing/logging/#logging-in-a-library).
Existing `logging.*` statements replaced with individual `logger` statements which are instantiated in the modules where they are used.
Users can now configure logging output by getting and configuring the logger with name `betfairlightweight`.

Configure logging

---

betfairlightweight/streaming/betfairstream.py
tests/test_betfairstream.py

I've moved the socket cleanup code into `stop` and called it before raising SocketError.
I had to modify one of the tests since it was expecting a SocketError but the stop code was causing a different exception to be thrown as the socket was mocked and it was trying to call a non-existent method.
Maybe it would have been better to mock the `shutdown` and `close` methods on the socket instead?

Call stop before raising SocketError in _read_loop

---

betfairlightweight/__init__.py
betfairlightweight/resources/streamingresources.py
tests/test_streamingresources.py

Hi Liam,
Additions and fixes so that the starting price object is available for the `RunnerBook`, without `sp` being available in the serialise function, was `RunnerBookSP` ever available?  The only thing I haven't changed (but maybe should do) is `RunnerBookSP`'s `actual_sp`.  I don't know what that should be per the exchange docs, http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API should it be removed?

 Starting price additions and bug fixes

---

betfairlightweight/resources/bettingresources.py

Size isn't returned when bet_target_type is BACKERS_PROFIT.

Set LimitOrder size to optional

---

.gitignore
betfairlightweight/__init__.py
betfairlightweight/resources/bettingresources.py
betfairlightweight/resources/racecardresources.py
betfairlightweight/resources/streamingresources.py

Specifically needed for MarketDefinition and MarketCatalogueDescription.  `list_market_catalogue` is currently broken because of the latter, and the entire stream will be broken (if you've requested the MarketDefinition with your stream), when that update comes through.
The BetFair docs haven't updated to define `PriceLadderDescription`, nor `KeyLineDefinition` fully yet, but I'll put a new PR with the new objects for that when they do.
Some other oddities handled in other places as well.

Handle more BetFair parameter turbulence and updates to their API

---

betfairlightweight/endpoints/login.py
tests/unit/test_login.py

By using a dict instead of a string, the requests library will URL encode the parameters which resolves issues with passwords which have special characters in them.
Closes #151

Use a dict for login parameters

---

betfairlightweight/streaming/cache.py
tests/unit/test_cache.py

I was playing around with some historical data and ran across a bug where the `rc` in an `img` update contained multiple objects/entries for the same selection. It looked something like:
```
{..."rc":[{"atb":[[1.01,200],[1.03,11.52],[1.02,22.98],[1.13,15.38]],"id":23537142},{"spn":"Infinity","spf":"NaN","id":23537142},...],"con":true,"img":true...}
```
This caused in issue where multiple `RunnerBook` objects were created and pushed into `MarketBookCache.runners` for the same runner. The `runner_dict` would have the correct number of selections since it was keyed off of the `id`, but lost data since it pointed to a single one of the `RunnerBook` objects for the selection that only contained part of the image.
I'm not very familiar with java, but in the reference implementation of the …

Fix bug when img rc contains multiple entries for the same selection

---

betfairlightweight/filters.py
tests/unit/test_filters.py

This change makes filters.py time_range() accept datetime arguments, while still allowing string parameters as it's been so far.

filters.py time_range: accept datetime arguments

---

betfairlightweight/streaming/listener.py
betfairlightweight/streaming/stream.py
docs/streaming.md
examples/examplestreaminghistorical.py
tests/unit/test_stream.py

max_latency can now be set to None to prevent warnings being displayed (annoying when backtesting as the latency is obviously very high)

closes #283

---

betfairlightweight/streaming/cache.py
betfairlightweight/streaming/stream.py
tests/unit/test_cache.py

streaming_update stored and passed to create_resource response
before this change backtesting did not contain the latest streaming_update

closes #318

---

betfairlightweight/endpoints/scores.py

Looking at the API for `list_race_details`, it looks like the types are incorrect:
https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Race+Status+API#RaceStatusAPI-racedetails
I've changed the `meeting_ids` and `race_ids` both to lists instead of `dict` and `str` respectively to avoid confusion.  This isn't actually correct as they should be `Optional[list]` as they default to `None`, but I see that throughout the code, where the `Optional` is ignored. As a general note, when I run `mypy` on the code base there are a lot errors, including a lot of these '...has incompatible type "Optional[X]"; expected "X"'.

Fix types for list_race_details

---

MANIFEST.in

Currently if you try to build from source (i.e `python setup.py install`), the build fails because `requirements-speed.txt` is not in the source distribution. This fixes the issue. I also changed the format to have one include per line for readability and diff'ing clarity.

Fix broken build from source due to missing requirements-speed.txt file

---

betfairlightweight/apiclient.py
betfairlightweight/baseclient.py
tests/unit/test_baseclient.py

Propagate up to BaseClient and APIClient the ability to use single file certificate (a '.pem' file, containing the private key and the certificate). Keep and prefer the existing crt/key file pair, but use tuple instead of list as keep more similar as used in the requests library.

Use single file (.pem) certificate.

---

betfairlightweight/exceptions.py

As per #312, this updates the exception classes to store the raw payloads in a way that can be pickled/unpickled directly, and formats the message as requested.
This shouldn't change the appearance when an exception gets raised, or `str(exc)`, but it does mean `repr(exc)` is different, as it shows the original arguments to the constructor. A custom `BetfairError.__repr__` could be used if desirable.
Using the example exception from the issue you can now pull out the underlying aping errors with eg - `exc.response['error']['data']['AccountAPINGException']`.

Ensure exceptions are picklable

---

MANIFEST.in

When attempting to run the test suite (`python -m unittest discover -s tests --verbose`) from the tarball on `pypi`, you get the following error:
```
======================================================================
ERROR: test_version (test_release.ReleaseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/conda/feedstock_root/build_artifacts/betfairlightweight_1644251545971/test_tmp/tests/test_release.py", line 10, in test_version
with open("HISTORY.rst", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
```
Since the `HISTORY.rst` is not included in the source distribution. I've added the file to the MANIFEST.in to address this.

Add HISTORY.rst to MANIFEST.in to fix broken release test

---

betfairlightweight/streaming/betfairstream.py
tests/test_betfairstream.py

This fixes an admitedly rare-in-practice issue where complete messages get stuck in a buffer but also speeds up the receiving of data from the socket in all cases.
The current socket code waits until the last received data ends with a linefeed. It's not gauarenteed that each messsage sent will be read by a single call to `socket.recv` - the message could be larger than the buffer, or several small messages could be read together. It's possible for complete messages to be stuck in the buffer until a call to `recv` returns bytes that end with a linefeed.
For the sake of illustrating the issue imagine the buffer is 16 bytes. We can `.recv` a full 16 bytes of data containing one complete and one partial message. (Note it's possible for this to happen even if the amount of received data is …

Improve performance of socket code

---

betfairlightweight/streaming/stream.py

This speeds up snap by splitting it into two cases, where market_ids is None or not.
If market_ids are specified then we can avoid construcing a list of all of self._caches.values(). To do this the walrus operator is used. This means that Python >= 3.8 is required, but that is already the oldest tested Python version.
If market_ids is None then we can avoid the conditional on market_ids being None or not on each iteration.
Benchmark:
https://gist.github.com/petedmarsh/71337df6a09d47e5f55d2f0d60e15cf7
```
Results (Python 3.11.3):
Benchmarks, repeat=5, number=5
┌──────────────────────────────────────────────────────────────────┬─────────┬─────────┬─────────┬────────────────┬─────────────────┬────────────────┐
│                                                        Benchmark │ Min     │ Max …
```

Improve performance of BaseStream.snap

---

betfairlightweight/streaming/betfairstream.py
betfairlightweight/streaming/listener.py
betfairlightweight/streaming/stream.py
examples/examplestreamingerrhandling.py
tests/test_listener.py

Logging like this:
logger.debug("Hello, %s" % name)
causes the message string to always be interpolated even if the message is not going to be logged.
Logging like this:
logger.debug("Hello, %s", name)
will mean the string is only ever interpolated if it will be logged.
In practice here this will make little difference if the log level is INFO
or above, but it does mean a `if` statement can be removed from StreamListener.
See:
https://docs.python.org/3/howto/logging.html#optimization
https://stackoverflow.com/questions/4148790/lazy-logger-message-string-evaluation

Lazily evaluate log message parameters
